### ISSUE TITLE
Design Update: 

### ISSUE THREAD

**Issue by metinbaris** [yuliia-p/BookLover#39]
Hey @yuliia-p noticed your test app on LinkedIn posts, it looks great!

There are few sign-up form improvements you can add such as :

- Email input has 'placeholder' typo
- Email input 'type' can be email for simple frontend validation
- Password could have 'minlength' attribute of 8
- Log-in link on the right bottom has typo (Logn in)

It's also good to validate them on backend if you like later.

Wish you the best

**Comment by yuliia-p** [comment]
Oh! Thanks a lot!
I really appreciate your help!
